# Generated by Django 4.2.3 on 2023-07-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('items', models.CharField(max_length=100)),
                ('lat_long', models.CharField(max_length=100)),
                ('full_details', models.TextField()),
            ],
        ),
    ]
