# Generated by Django 4.2.3 on 2023-07-19 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dish',
            new_name='Restaurant',
        ),
    ]
